version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d truepositive" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - db

  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE
    command: app/start-web.sh
    volumes:
      - media:/app/api/media
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db

  bot:
    container_name: telegram_bot
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    command: app/start-bot.sh
    restart: always
    environment:
      - ./.env
    depends_on:
      - api
    networks:
      - db


volumes:
  pgdata:
  media:
networks:
  db: