# Generated by Django 5.0.4 on 2024-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=10)),
            ],
        ),
    ]
